'use client';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowUpRight, ChevronDown } from 'lucide-react';
import type { FAQ, Product } from '@/types';

export function Reveal({ children, className='' }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} initial={{ opacity:0, y:18 }} whileInView={{ opacity:1, y:0 }} viewport={{ once:true, margin:'-50px' }} transition={{ duration:.65, ease:[.2,.65,.3,1] }}>{children}</motion.div>; }
export function SectionHeading({ eyebrow, title, copy, dark=false }: { eyebrow:string; title:string; copy?:string; dark?:boolean }) { return <div className={`max-w-2xl ${dark?'text-ivory':''}`}><p className="eyebrow">{eyebrow}</p><h2 className="display mt-4 text-5xl sm:text-6xl lg:text-7xl">{title}</h2>{copy&&<p className={`mt-6 max-w-xl text-sm leading-7 ${dark?'text-stone/80':'text-ink/65'}`}>{copy}</p>}</div>; }
export function TextLink({ href, children }: { href:string; children:React.ReactNode }) { return <Link href={href} className="inline-flex items-center gap-2 border-b border-champagne pb-1 text-xs font-bold uppercase tracking-[.14em] text-champagne transition hover:text-bronze">{children}<ArrowUpRight size={14}/></Link> }
export function ProductCard({ product }: { product: Product }) { return <article className="group"><Link href={`/collections/${product.slug}`} className="block overflow-hidden bg-stone"><img src={product.image} alt={product.name} className="image-zoom aspect-[4/5] w-full object-cover"/></Link><div className="pt-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-champagne">{product.category}</p><div className="mt-2 flex items-start justify-between gap-3"><h3 className="font-display text-3xl leading-none">{product.name}</h3><Link aria-label={`View ${product.name}`} href={`/collections/${product.slug}`} className="mt-1 rounded-full border border-stone p-2 transition hover:border-ink"><ArrowUpRight size={15}/></Link></div><p className="mt-3 text-xs text-ink/60">{product.dimensions} <span className="mx-1">·</span> {product.finish}</p></div></article> }
export function FAQList({ items }: { items: FAQ[] }) { return <div className="divide-y divide-stone">{items.map((item) => <details key={item.question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-2xl sm:text-3xl">{item.question}<ChevronDown className="shrink-0 transition group-open:rotate-180" size={20}/></summary><p className="max-w-2xl pt-4 text-sm leading-7 text-ink/65">{item.answer}</p></details>)}</div> }
