'use client';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowUpRight, ChevronDown } from 'lucide-react';
import type { FAQ, Product } from '@/types';

export function Reveal({ children, className='' }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} initial={{ opacity:0, y:18 }} whileInView={{ opacity:1, y:0 }} viewport={{ once:true, margin:'-50px' }} transition={{ duration:.65, ease:[.2,.65,.3,1] }}>{children}</motion.div>; }
export function SectionHeading({ eyebrow, title, copy, dark=false }: { eyebrow:string; title:string; copy?:string; dark?:boolean }) { return <div className={`max-w-2xl ${dark?'text-white':''}`}><p className="eyebrow">{eyebrow}</p><h2 className="display mt-4 text-5xl sm:text-6xl lg:text-7xl">{title}</h2>{copy&&<p className={`mt-6 max-w-xl text-sm leading-7 ${dark?'text-white/60':'text-ink/60'}`}>{copy}</p>}</div>; }
export function TextLink({ href, children }: { href:string; children:React.ReactNode }) { return <Link href={href} className="group mt-8 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-champagne"><span className="border-b border-champagne/50 pb-1 transition group-hover:border-champagne">{children}</span><ArrowUpRight size={14} className="transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5"/></Link> }
export function ProductCard({ product }: { product: Product }) { return <article className="group"><Link href={`/collections/${product.slug}`} className="relative block overflow-hidden rounded-[1.25rem] bg-stone"><img src={product.image} alt={product.name} className="image-zoom aspect-[4/5] w-full object-cover"/><div className="absolute inset-x-0 bottom-0 translate-y-full bg-gradient-to-t from-ink/90 to-transparent p-5 text-white transition duration-500 group-hover:translate-y-0"><span className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em]">View piece <ArrowUpRight size={14}/></span></div></Link><div className="px-1 pt-5"><p className="text-[9px] font-bold uppercase tracking-[.17em] text-champagne">{product.category}</p><div className="mt-2 flex items-start justify-between gap-3"><h3 className="font-display text-3xl leading-none">{product.name}</h3><Link aria-label={`View ${product.name}`} href={`/collections/${product.slug}`} className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-ink text-white transition duration-300 hover:bg-champagne hover:text-ink"><ArrowUpRight size={14}/></Link></div><p className="mt-3 text-[11px] text-ink/50">{product.dimensions} <span className="mx-1">·</span> {product.finish}</p></div></article> }
export function FAQList({ items }: { items: FAQ[] }) { return <div className="divide-y divide-ink/15">{items.map((item, index) => <details key={item.question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-2xl sm:text-3xl"><span><em className="mr-4 text-base not-italic text-champagne">0{index+1}</em>{item.question}</span><ChevronDown className="shrink-0 transition duration-300 group-open:rotate-180" size={20}/></summary><p className="max-w-2xl pt-5 pl-9 text-sm leading-7 text-ink/60">{item.answer}</p></details>)}</div> }
