server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        return 301 https://shreesaicreation.com$request_uri;
    }
}

server {
    server_name shreesaicreation.com www.shreesaicreation.com; # managed by Certbot

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/shreesaicreation.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shreesaicreation.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 80 ;
    listen [::]:80 ;
    server_name shreesaicreation.com www.shreesaicreation.com;
    return 301 https://shreesaicreation.com$request_uri;
}

server {
    server_name www.shreesaicreation.org www.shreesaicreation.online www.shreesaicreation.com.au shreesaicreation.online shreesaicreation.com.au shreesaicreation.org; # managed by Certbot

    location / {
        return 301 https://shreesaicreation.com$request_uri;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/shreesaicreation.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shreesaicreation.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 80 ;
    listen [::]:80 ;
    server_name www.shreesaicreation.org www.shreesaicreation.online www.shreesaicreation.com.au shreesaicreation.online shreesaicreation.com.au shreesaicreation.org;
    return 301 https://shreesaicreation.com$request_uri;
}
