'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowUp, Menu, MessageCircle, Phone, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { NavigationItem, SiteSettings } from '@/types';

export function Logo({ light = false }: { light?: boolean }) { return <Link href="/" className={`relative z-10 font-display text-[29px] leading-[.7] tracking-[-.04em] ${light ? 'text-white' : 'text-ink'}`}><span className="mb-1 block font-sans text-[8px] font-bold uppercase tracking-[.42em] text-champagne">Shree Sai</span>Creation</Link>; }

export function Header({ navigation }: { navigation: NavigationItem[] }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const heroPage = !['/login', '/signup', '/signin', '/forgot-password'].includes(pathname) && !pathname.startsWith('/collections/') && !pathname.startsWith('/blog/');
  useEffect(() => { const update = () => setScrolled(window.scrollY > 16); update(); window.addEventListener('scroll', update); return () => window.removeEventListener('scroll', update); }, []);
  return <header className={`sticky top-0 z-50 px-3 transition duration-500 sm:px-5 ${scrolled ? 'pt-2' : 'pt-0'}`}><div className={`mx-auto flex h-[72px] max-w-[1520px] items-center justify-between rounded-b-2xl px-4 transition duration-500 sm:px-6 ${scrolled ? 'border border-white/10 bg-ink/90 shadow-2xl backdrop-blur-xl' : heroPage ? 'border-b border-white/10 bg-ink/10 backdrop-blur-md' : 'border-b border-ink/10 bg-ivory/80 backdrop-blur-md'}`}><Logo light={scrolled || heroPage}/><nav className="hidden h-full items-center gap-7 lg:flex">{navigation.map((item) => <Link className={`relative flex h-full items-center text-[10px] font-bold uppercase tracking-[.14em] transition after:absolute after:bottom-4 after:h-px after:bg-champagne after:transition-all ${pathname === item.href ? 'text-champagne after:w-full' : `${scrolled || heroPage ? 'text-white/65 hover:text-white' : 'text-ink/60 hover:text-ink'} after:w-0 hover:after:w-full`}`} href={item.href} key={item.href}>{item.label}</Link>)}</nav><div className="hidden items-center gap-4 lg:flex"><Link href="/login" className={`text-[10px] font-bold uppercase tracking-[.14em] ${scrolled || heroPage ? 'text-white/60' : 'text-ink/60'}`}>Sign in</Link><Link href="/contact" className="button-gold">Start a project</Link></div><button onClick={() => setOpen(!open)} className={`grid h-10 w-10 place-items-center rounded-full border lg:hidden ${scrolled || heroPage ? 'border-white/20 text-white' : 'border-ink/15 text-ink'}`} aria-label="Toggle menu">{open ? <X size={18}/> : <Menu size={18}/>}</button></div>{open && <div className="mx-auto max-w-[1520px] overflow-hidden rounded-b-2xl bg-ink px-7 py-8 text-white shadow-2xl lg:hidden"><nav className="flex flex-col gap-5">{navigation.map(item => <Link onClick={() => setOpen(false)} className="font-display text-4xl tracking-[-.04em]" href={item.href} key={item.href}>{item.label}</Link>)}<div className="mt-2 flex gap-3"><Link onClick={() => setOpen(false)} href="/login" className="button-line border-white/40 text-white hover:bg-white hover:text-ink">Sign in</Link><Link onClick={() => setOpen(false)} href="/contact" className="button-gold">Enquire now</Link></div></nav></div>}</header>;
}

export function Footer({ settings, navigation }: { settings: SiteSettings; navigation: NavigationItem[] }) { return <><footer className="overflow-hidden bg-ink text-white"><div className="container-luxe pt-20 sm:pt-28"><div className="flex flex-col justify-between gap-8 border-b border-white/10 pb-14 lg:flex-row lg:items-end"><div><p className="eyebrow">Make an entrance</p><h2 className="display mt-4 max-w-4xl text-5xl leading-[.88] sm:text-7xl">A room changes when the <em className="text-champagne">light</em> is right.</h2></div><Link href="/contact" className="button-gold shrink-0">Book consultation</Link></div><div className="grid gap-12 py-14 sm:grid-cols-2 lg:grid-cols-[1.25fr_.8fr_.8fr_1fr]"><div><Logo light/><p className="mt-7 max-w-xs text-sm leading-7 text-white/55">Bespoke chandeliers and decorative lighting for homes and projects of distinction.</p></div><FooterList title="Navigate" links={navigation.slice(1)}/><FooterList title="Collections" links={[{ label:'Crystal chandeliers',href:'/collections' },{ label:'Modern forms',href:'/collections' },{ label:'Bespoke lighting',href:'/bespoke' },{ label:'Pendant lights',href:'/collections' }]}/><div><p className="eyebrow">Visit or enquire</p><a href={`tel:${settings.phone.replace(/\s/g,'')}`} className="mt-6 block font-display text-3xl">{settings.phone}</a><a href={`mailto:${settings.email}`} className="mt-3 block text-sm text-white/55">{settings.email}</a><p className="mt-5 max-w-[220px] text-xs leading-5 text-white/45">{settings.address}</p><a href={`https://wa.me/${settings.whatsapp}`} className="mt-5 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-champagne"><MessageCircle size={15}/> WhatsApp</a></div></div><div className="flex flex-col justify-between gap-3 border-t border-white/10 py-6 text-[10px] font-bold uppercase tracking-[.13em] text-white/35 sm:flex-row"><span>© {new Date().getFullYear()} Shree Sai Creation</span><span>Luxury lighting, made personal</span></div></div></footer><FloatingActions whatsapp={settings.whatsapp} phone={settings.phone}/></>; }

function FooterList({ title, links }: { title:string; links:NavigationItem[] }) { return <div><p className="eyebrow">{title}</p><div className="mt-6 flex flex-col gap-3.5">{links.map(link => <Link key={link.href + link.label} href={link.href} className="text-sm text-white/60 transition hover:text-champagne">{link.label}</Link>)}</div></div>; }
function FloatingActions({ whatsapp, phone }: { whatsapp:string; phone:string }) { const [visible, setVisible] = useState(false); useEffect(() => { const update = () => setVisible(window.scrollY > 600); window.addEventListener('scroll', update); return () => window.removeEventListener('scroll', update); }, []); return <div className="fixed bottom-5 right-5 z-40 flex flex-col gap-2"><a aria-label="Call us" href={`tel:${phone.replace(/\s/g,'')}`} className="grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-ink text-white shadow-xl transition hover:-translate-y-1 hover:bg-champagne hover:text-ink"><Phone size={17}/></a><a aria-label="WhatsApp us" href={`https://wa.me/${whatsapp}`} className="grid h-11 w-11 place-items-center rounded-full bg-champagne text-ink shadow-glow transition hover:-translate-y-1"><MessageCircle size={19}/></a>{visible && <button aria-label="Back to top" onClick={() => window.scrollTo({ top:0, behavior:'smooth' })} className="grid h-11 w-11 place-items-center rounded-full bg-white text-ink shadow-xl transition hover:-translate-y-1"><ArrowUp size={18}/></button>}</div>; }
