'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Menu, X, MessageCircle } from 'lucide-react';
import { useState } from 'react';
import { navigation, settings } from '@/data/site-data';
export function Logo({ light=false }: { light?:boolean }) { return <Link href="/" className={`font-display text-2xl leading-[.8] ${light?'text-ivory':'text-ink'}`}><span className="block text-[10px] font-sans font-bold uppercase tracking-[.28em] text-champagne">Shree Sai</span>Creation</Link> }
export function Header() { const path=usePathname(); const [open,setOpen]=useState(false); return <header className="sticky top-0 z-50 border-b border-stone/70 bg-ivory/90 backdrop-blur"><div className="container-luxe flex h-[76px] items-center justify-between"><Logo/><nav className="hidden items-center gap-7 lg:flex">{navigation.map(n=><Link className={`text-[11px] font-bold uppercase tracking-[.12em] transition hover:text-champagne ${path===n.href?'text-champagne':'text-ink/70'}`} href={n.href} key={n.href}>{n.label}</Link>)}</nav><div className="hidden lg:flex"><Link href="/contact" className="button-gold">Enquire now</Link></div><button onClick={()=>setOpen(!open)} className="p-2 lg:hidden" aria-label="Open menu">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-stone bg-ivory px-5 py-7 lg:hidden"><nav className="flex flex-col gap-5">{navigation.map(n=><Link onClick={()=>setOpen(false)} className="font-display text-3xl" href={n.href} key={n.href}>{n.label}</Link>)}<Link href="/contact" className="button-gold mt-3">Enquire now</Link></nav></div>}</header> }
export function Footer() { return <footer className="bg-ink text-ivory"><div className="container-luxe grid gap-12 py-16 sm:grid-cols-2 lg:grid-cols-[1.3fr_1fr_1fr_1.2fr]"><div><Logo light/><p className="mt-6 max-w-xs text-sm leading-7 text-stone/75">Statement lighting and bespoke chandeliers for interiors with a point of view.</p></div><div><p className="eyebrow">Explore</p><div className="mt-5 flex flex-col gap-3 text-sm text-stone/80">{navigation.slice(1).map(n=><Link href={n.href} key={n.href} className="hover:text-champagne">{n.label}</Link>)}</div></div><div><p className="eyebrow">Collections</p><div className="mt-5 flex flex-col gap-3 text-sm text-stone/80"><Link href="/collections">Crystal Chandeliers</Link><Link href="/collections">Modern Chandeliers</Link><Link href="/collections">Bespoke Lighting</Link><Link href="/collections">Pendant Lights</Link></div></div><div><p className="eyebrow">Begin a project</p><a href={`tel:${settings.phone.replace(/\s/g,'')}`} className="mt-5 block font-display text-3xl">{settings.phone}</a><a href={`mailto:${settings.email}`} className="mt-3 block text-sm text-stone/80">{settings.email}</a><a href={`https://wa.me/${settings.whatsapp}`} className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-champagne"><MessageCircle size={15}/> WhatsApp us</a></div></div><div className="border-t border-white/10"><div className="container-luxe flex flex-col gap-2 py-5 text-[10px] uppercase tracking-[.12em] text-stone/50 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} Shree Sai Creation</span><span>Designed for extraordinary spaces</span></div></div></footer> }
