import Link from 'next/link';
import { ArrowDown, ArrowRight, ArrowUpRight, Gem, MapPin, PenTool, Ruler, ShieldCheck, Sparkles } from 'lucide-react';
import { getHomeContent } from '@/lib/content-repository';
import { ProductCard, Reveal, SectionHeading, TextLink } from '@/components/shared/ui';
import { BeforeAfter } from '@/components/home/before-after';

const reasons = [['Custom Design Support', PenTool], ['Exceptional Materials', Gem], ['Artisan Detail', Sparkles], ['Architectural Scale', Ruler], ['Pan-India Delivery', MapPin], ['Guided Installation', ShieldCheck]];
const statistics = [['1500+', 'Projects illuminated'], ['20+', 'Years of craft'], ['98%', 'Client satisfaction'], ['50+', 'Cities reached']];

export default async function Home() {
  const { categories, featuredProducts, projects, testimonials } = await getHomeContent();
  return <main>
    <section className="relative -mt-[72px] min-h-screen overflow-hidden bg-ink text-white">
      <img className="absolute inset-0 h-full w-full scale-105 object-cover opacity-55 drift" src="https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=2400&q=90" alt="Grand crystal chandelier"/>
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(11,15,25,.9)_0%,rgba(11,15,25,.5)_48%,rgba(11,15,25,.1)_100%)]"/>
      <div className="absolute inset-x-0 bottom-0 h-2/5 bg-gradient-to-t from-ink to-transparent"/>
      <div className="container-luxe relative flex min-h-screen flex-col justify-end pb-12 pt-32 sm:pb-16"><Reveal><p className="eyebrow">Atelier of illumination · Est. 2006</p><h1 className="display mt-5 max-w-5xl text-[4.1rem] sm:text-8xl md:text-9xl lg:text-[9.2rem]">The art of <em className="font-normal text-champagne">arrival.</em></h1><p className="mt-7 max-w-md text-sm leading-7 text-white/70 sm:text-base">Sculptural chandeliers and bespoke lighting created for the homes, hotels and interiors that refuse the ordinary.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/collections" className="button-gold">Explore the collection <ArrowUpRight size={15}/></Link><Link href="/bespoke" className="button-line border-white/40 text-white hover:bg-white hover:text-ink">Commission a piece</Link></div></Reveal><div className="mt-14 flex items-end justify-between"><a href="#introduction" className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.18em] text-white/50"><span className="grid h-8 w-8 place-items-center rounded-full border border-white/20"><ArrowDown size={13}/></span> Scroll to discover</a><p className="hidden max-w-[190px] text-right text-[10px] uppercase leading-5 tracking-[.16em] text-white/40 sm:block">Made for interiors with a point of view</p></div></div>
    </section>
    <section id="introduction" className="section-space overflow-hidden bg-ivory"><div className="container-luxe grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><Reveal><p className="eyebrow">Shree Sai Creation</p><p className="mt-5 font-display text-3xl leading-[.95] text-ink/55">A studio built around the transformative power of light.</p></Reveal><Reveal><h2 className="display max-w-4xl text-5xl sm:text-7xl lg:text-8xl">Every room has a <em className="text-champagne">defining</em> moment.</h2><p className="mt-8 max-w-xl text-base leading-8 text-ink/60">We make the piece that creates it—combining material, scale and atmosphere into lighting that feels native to your architecture.</p><TextLink href="/about">Enter our world</TextLink></Reveal></div></section>
    <section className="overflow-hidden bg-midnight py-6 text-white"><div className="marquee-track flex w-max gap-14 whitespace-nowrap text-[11px] font-bold uppercase tracking-[.23em] text-white/70">{Array.from({ length: 2 }, () => ['Custom chandeliers', 'Architectural lighting', 'Hand-finished metalwork', 'Crystal compositions', 'Lighting consultation']).flat().map((item, index) => <span className="flex items-center gap-14" key={`${item}-${index}`}><i className="h-1.5 w-1.5 rounded-full bg-champagne"/>{item}</span>)}</div></section>
    <section className="section-space bg-ink text-white"><div className="container-luxe"><div className="flex flex-wrap items-end justify-between gap-8"><SectionHeading dark eyebrow="The collection" title="Light, with a signature." copy="From quiet sculptural forms to installations with dramatic presence."/><Link href="/collections" className="button-line border-white/30 text-white hover:bg-white hover:text-ink">See all collections <ArrowRight size={14}/></Link></div><div className="mt-14 flex snap-x gap-4 overflow-x-auto pb-3 [scrollbar-width:none]">{categories.map((category, index) => <Reveal className="min-w-[78vw] snap-start sm:min-w-[42vw] lg:min-w-[28vw]" key={category.id}><Link href={`/collections?category=${category.id}`} className="group relative block aspect-[4/5] overflow-hidden rounded-[1.5rem]"><img src={category.image} alt={category.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-110"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/10 to-transparent"/><div className="absolute left-6 top-6 grid h-9 w-9 place-items-center rounded-full border border-white/20 bg-white/10 text-xs backdrop-blur">0{index + 1}</div><div className="absolute inset-x-0 bottom-0 p-6"><p className="font-display text-4xl">{category.name}</p><p className="mt-2 max-w-xs text-xs leading-5 text-white/60">{category.description}</p><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-champagne">Discover <ArrowUpRight size={14}/></span></div></Link></Reveal>)}</div></div></section>
    <section className="bg-ivory py-10 sm:py-16"><div className="container-luxe grid overflow-hidden rounded-[2rem] bg-[#e6e8ec] sm:grid-cols-2 lg:grid-cols-4">{statistics.map(([value, label]) => <div key={label} className="border-b border-ink/10 px-7 py-8 last:border-0 lg:border-b-0 lg:border-r lg:last:border-r-0"><p className="font-display text-5xl text-ink sm:text-6xl">{value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.15em] text-ink/50">{label}</p></div>)}</div></section>
    <section className="section-space bg-ivory"><div className="container-luxe"><div className="flex flex-wrap items-end justify-between gap-8"><SectionHeading eyebrow="Signature pieces" title="Designed to be remembered."/><TextLink href="/collections">View every piece</TextLink></div><div className="mt-14 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{featuredProducts.slice(0, 8).map(product => <ProductCard key={product.id} product={product}/>)}</div></div></section>
    <section className="bg-ink text-white"><div className="grid lg:grid-cols-2"><div className="relative min-h-[520px] overflow-hidden"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85" alt="Bespoke chandelier in a double-height foyer" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-ink/80 to-transparent"/><p className="absolute bottom-7 left-7 text-[10px] font-bold uppercase tracking-[.16em] text-white/60">Private villa · Mumbai</p></div><div className="container-luxe flex items-center py-24 lg:px-16"><div className="max-w-xl"><SectionHeading dark eyebrow="Bespoke atelier" title="One space. One singular piece." copy="We translate the character of your architecture into a lighting composition with its own gravity."/><div className="mt-10 grid grid-cols-2 gap-x-8 gap-y-5 border-t border-white/15 pt-7 text-[10px] font-bold uppercase tracking-[.12em] text-white/60"><span>01 / Scale study</span><span>02 / Material direction</span><span>03 / Technical drawings</span><span>04 / White-glove delivery</span></div><Link href="/bespoke" className="button-gold mt-10">Create a bespoke piece <ArrowUpRight size={15}/></Link></div></div></div></section>
    <section className="section-space bg-ivory"><div className="container-luxe grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><SectionHeading eyebrow="The transformation" title="Visualise the difference light can make." copy="Drag through a living space before and after a bespoke lighting composition."/><BeforeAfter/></div></section>
    <section className="section-space bg-[#e9ebef]"><div className="container-luxe"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><SectionHeading eyebrow="Why Shree Sai" title="Craft without compromise." copy="A considered partner for homeowners, designers and architects who care about every last detail."/><div className="grid grid-cols-2 gap-x-6 gap-y-10">{reasons.map(([label, Icon]) => { const ItemIcon = Icon as typeof Gem; return <Reveal key={label as string}><div className="grid h-11 w-11 place-items-center rounded-full bg-white text-champagne shadow-luxe"><ItemIcon size={19} strokeWidth={1.5}/></div><h3 className="mt-5 font-display text-3xl leading-none">{label as string}</h3><p className="mt-3 text-xs leading-6 text-ink/55">Specified with care, realised with precision.</p></Reveal>; })}</div></div></div></section>
    <section className="section-space bg-ink text-white"><div className="container-luxe"><div className="flex flex-wrap items-end justify-between gap-8"><SectionHeading dark eyebrow="In context" title="Architecture, illuminated."/><TextLink href="/projects">Explore all projects</TextLink></div><div className="mt-14 grid gap-4 md:grid-cols-12">{projects.slice(0, 3).map((project, index) => <Link href="/projects" key={project.slug} className={`group relative overflow-hidden rounded-[1.5rem] ${index === 0 ? 'min-h-[500px] md:col-span-7' : 'min-h-[290px] md:col-span-5'}`}><img src={project.image} alt={project.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-ink/90 via-ink/5 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7"><p className="eyebrow">{project.type} · {project.location}</p><p className="mt-3 font-display text-4xl">{project.title}</p><p className="mt-3 max-w-sm text-xs leading-5 text-white/60">{project.description}</p></div></Link>)}</div></div></section>
    <section className="border-y border-ink/10 bg-ivory py-9"><div className="container-luxe"><p className="mb-7 text-center text-[9px] font-bold uppercase tracking-[.22em] text-ink/40">Trusted in collaboration with leading design practices</p><div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-5 font-display text-2xl tracking-[-.04em] text-ink/35 sm:gap-x-16"><span>ATELIER NINE</span><span>FORM & SPACE</span><span>STUDIO ALINE</span><span>ARCADIA</span><span>THE HABITAT CO.</span></div></div></section>
    <section className="section-space bg-ivory"><div className="container-luxe"><p className="eyebrow">Client notes</p><div className="mt-8 grid gap-5 lg:grid-cols-2">{testimonials.slice(0, 2).map((testimonial, index) => <Reveal key={testimonial.name}><article className="relative min-h-[280px] overflow-hidden rounded-[1.5rem] bg-[#e9ebef] p-8 sm:p-11"><span className="font-display text-7xl leading-none text-champagne/50">0{index + 1}</span><p className="mt-6 max-w-xl font-display text-3xl leading-tight sm:text-4xl">“{testimonial.quote}”</p><div className="mt-8"><p className="text-[10px] font-bold uppercase tracking-[.16em]">{testimonial.name}</p><p className="mt-1 text-xs text-ink/50">{testimonial.role}</p></div></article></Reveal>)}</div></div></section>
    <section className="relative overflow-hidden bg-champagne px-5 py-24 text-center text-ink sm:py-32"><div className="absolute -left-24 top-0 h-64 w-64 rounded-full border border-ink/10"/><div className="absolute -bottom-32 -right-20 h-80 w-80 rounded-full border border-ink/10"/><div className="relative mx-auto max-w-4xl"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-ink/60">The next chapter begins here</p><h2 className="display mt-5 text-5xl sm:text-7xl">Let’s make your space unforgettable.</h2><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/contact" className="button-line border-ink bg-ink text-white hover:bg-white hover:text-ink">Book a consultation</Link><Link href="/collections" className="button-line border-ink">View catalogue</Link></div></div></section>
  </main>;
}
