import Link from 'next/link';
import { ArrowDown, ArrowUpRight, Gem, Ruler, Sparkles, MapPin, ShieldCheck, PenTool } from 'lucide-react';
import { categories, products, projects, testimonials } from '@/data/site-data';
import { ProductCard, Reveal, SectionHeading, TextLink } from '@/components/shared/ui';

const reasons=[['Custom Design Support',PenTool],['Exceptional Materials',Gem],['Elegant Craftsmanship',Sparkles],['Tailored Scale & Finish',Ruler],['Pan-India Projects',MapPin],['Guided Installation',ShieldCheck]];
export default function Home() { return <main>
 <section className="relative min-h-[calc(100svh-76px)] overflow-hidden bg-ink text-ivory"><img src="https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=2200&q=90" alt="Crystal chandelier in a refined interior" className="absolute inset-0 h-full w-full object-cover opacity-65"/><div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/40 to-black/10"/><div className="container-luxe relative flex min-h-[calc(100svh-76px)] flex-col justify-end pb-16 pt-32 sm:pb-20"><Reveal><p className="eyebrow">Lighting, considered</p><h1 className="display mt-5 max-w-4xl text-6xl sm:text-7xl md:text-8xl lg:text-[7.5rem]">Illuminate spaces with <em className="font-normal text-champagne">timeless</em> luxury.</h1><p className="mt-7 max-w-lg text-sm leading-7 text-stone/90">Bespoke chandeliers and decorative lighting, crafted to give exceptional interiors their defining moment.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/collections" className="button-gold">Explore collection <ArrowUpRight size={15}/></Link><Link href="/bespoke" className="button-line border-ivory text-ivory hover:bg-ivory hover:text-ink">Book consultation</Link></div></Reveal><a href="#introduction" className="mt-14 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.2em] text-stone/75"><ArrowDown size={15}/> Discover Shree Sai</a></div></section>
 <section id="introduction" className="section-space container-luxe grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><Reveal><p className="eyebrow">The art of illumination</p><h2 className="display mt-4 max-w-md text-5xl sm:text-6xl">Light that feels <em className="text-champagne">personal.</em></h2></Reveal><Reveal><p className="max-w-2xl text-xl leading-9 text-ink/75">Shree Sai Creation brings together luminous craft, fine materials and a considered understanding of interior scale. From private homes to landmark hospitality spaces, we create light that belongs to the architecture around it.</p><TextLink href="/about">Our story</TextLink></Reveal></section>
 <section className="bg-ink py-20 text-ivory sm:py-28"><div className="container-luxe"><SectionHeading dark eyebrow="Curated collections" title="A signature for every space." copy="Discover collections shaped around material, mood and proportion."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((c,i)=><Reveal key={c.id}><Link href={`/collections?category=${c.id}`} className="group relative block aspect-[4/4.5] overflow-hidden"><img src={c.image} alt={c.name} className="image-zoom h-full w-full object-cover opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><p className="font-display text-3xl">{c.name}</p><p className="mt-2 text-xs leading-5 text-stone/75">{c.description}</p></div></Link></Reveal>)}</div></div></section>
 <section className="section-space container-luxe"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Made with intent" title="Crafted around your vision." copy="Every detail is considered with the same care as the room it will illuminate."/><div className="grid grid-cols-2 gap-x-7 gap-y-10 sm:grid-cols-3">{reasons.map(([name,Icon])=>{const I=Icon as typeof Gem; return <Reveal key={name as string}><I className="text-champagne" strokeWidth={1.3}/><h3 className="mt-4 font-display text-2xl">{name as string}</h3><p className="mt-2 text-xs leading-5 text-ink/55">Designed to bring clarity, character and lasting quality to your project.</p></Reveal>})}</div></div></section>
 <section className="section-space bg-[#ede9e1]"><div className="container-luxe"><div className="flex flex-wrap items-end justify-between gap-8"><SectionHeading eyebrow="The signature edit" title="Objects of light."/><TextLink href="/collections">View all pieces</TextLink></div><div className="mt-12 grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,8).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
 <section className="grid bg-ink text-ivory lg:grid-cols-2"><div className="min-h-[470px] overflow-hidden"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85" alt="Custom staircase chandelier" className="h-full w-full object-cover"/></div><div className="container-luxe flex items-center py-20 lg:px-16"><div className="max-w-xl"><SectionHeading dark eyebrow="Bespoke, by design" title="Made for the space only you have." copy="From the first sketch to final suspension, our bespoke service turns architectural possibility into a singular lighting piece."/><div className="mt-8 grid grid-cols-2 gap-4 text-xs text-stone/80"><span>01 — Scale & proportion</span><span>02 — Crystal & finish</span><span>03 — Technical drawings</span><span>04 — Installation support</span></div><Link href="/bespoke" className="button-gold mt-9">Start a bespoke project <ArrowUpRight size={15}/></Link></div></div></section>
 <section className="section-space container-luxe"><div className="flex flex-wrap items-end justify-between gap-8"><SectionHeading eyebrow="Selected installations" title="Light, in context." copy="A glimpse into the spaces we have had the privilege to illuminate."/><TextLink href="/projects">See all projects</TextLink></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{projects.slice(0,3).map(p=><Link href="/projects" key={p.slug} className="group relative aspect-[4/5] overflow-hidden"><img src={p.image} alt={p.title} className="image-zoom h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-ivory"><p className="eyebrow">{p.type} · {p.location}</p><h3 className="mt-2 font-display text-3xl">{p.title}</h3></div></Link>)}</div></section>
 <section className="bg-[#d9cfbd] py-20 sm:py-28"><div className="container-luxe"><p className="eyebrow">In their words</p><div className="mt-8 grid gap-5 md:grid-cols-2">{testimonials.map(t=><article key={t.name} className="bg-ivory p-7 sm:p-10"><p className="font-display text-3xl leading-tight sm:text-4xl">“{t.quote}”</p><p className="mt-8 text-xs font-bold uppercase tracking-[.13em]">{t.name}</p><p className="mt-1 text-xs text-ink/55">{t.role}</p></article>)}</div></div></section>
 <section className="bg-ink py-24 text-center text-ivory sm:py-32"><div className="container-luxe"><p className="eyebrow">Your next statement</p><h2 className="display mx-auto mt-5 max-w-4xl text-5xl sm:text-7xl">Looking for a chandelier that transforms your space?</h2><Link href="/contact" className="button-gold mt-9">Request a consultation <ArrowUpRight size={15}/></Link></div></section>
 </main> }
